prowjob_namespace: prow
pod_namespace: test-pods
log_level: debug
in_repo_config:
  enabled:
    '*': true
deck:
  spyglass:
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
      - lens:
          config: null
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - .*/junit.*\.xml
      - lens:
          name: podinfo
        required_files:
          - podinfo.json
plank:
  job_url_prefix_config:
    '*': 'https://prow.undistro.io/view/'
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 1m
  report_templates:
    '*': >-
      [Full PR test
      history](https://prow.undistro.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with
      index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR
      dashboard](https://prow.undistro.io/pr?query=is:pr+state:open+author:{{with
      index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    '*':
      gcs_configuration:
        bucket: 'getup-prow-logs-dev'
        default_org: getupio-undistro
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
      grace_period: 60s
      utility_images:
        clonerefs: 'gcr.io/k8s-prow/clonerefs:v20210310-a49501d5de'
        entrypoint: 'gcr.io/k8s-prow/entrypoint:v20210310-a49501d5de'
        initupload: 'gcr.io/k8s-prow/initupload:v20210310-a49501d5de'
        sidecar: 'gcr.io/k8s-prow/sidecar:v20210310-a49501d5de'

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m

tide:
  queries:
    - labels:
        - lgtm
        - approved
      missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
      orgs:
        - getupio-undistro
decorate_all_jobs: true

presets:

  - labels:
      preset-dind-enabled: 'true'
    volumes:
      - name: dockersock
        hostPath:
          path: "/var/run/docker.sock"
          type: Socket
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"

  - labels:
      preset-gh-token: 'true'
    env:
      - name: DOCKER_LOGIN
        value: felipeweb
      - name: DOCKER_PASSWORD
        value: fe99309974
      - name: GITHUB_TOKEN
        value: 3d97694d6df0b8e0a6cff78bfd16d9a458b26816

        
  - labels:
      preset-aws-cred-s3: 'true'
    volumes:
      - name: aws-creds-s3
        secret:
          defaultMode: 420
          secretName: aws-creds-s3
    volumeMounts:
      - name: aws-creds-s3
        mountPath: /root/.aws/
        readOnly: true

  - labels:
      preset-aws-cred-vpc: 'true'
    env:
      - name: AWS_DEFAULT_REGION
        value: us-east-1
    volumes:
      - name: aws-creds-vpc
        secret:
          defaultMode: 420
          secretName: aws-creds-vpc
    volumeMounts:
      - name: aws-creds-vpc
        mountPath: /root/.aws/
        readOnly: true
        

periodics:
  - interval: 1440m #Used to be 1m
    agent: kubernetes
    name: aws-vpc-list
    decorate: true
    labels:
      preset-aws-cred-vpc: 'true'
    spec:
      containers:
        - image: amazon/aws-cli
          command:
            - /bin/bash
            - '-c'
            - '--'
          args:
            - aws ec2 describe-vpcs
      nodeSelector:
        cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high
          
presubmits:
  getupio-undistro/undistro:
    - name: pull-undistro-build-manager
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        bucket: 'gs://getup-prow-logs-dev'
        path_strategy: explicit
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - manager
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test
        
    - name: pull-undistro-build-CLI
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        bucket: 'gs://getup-prow-logs-dev'
        path_strategy: explicit
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - cli
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test
        
    - name: pull-undistro-test
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - test
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high  
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test


postsubmits:
  getupio-undistro/undistro:
    - name: pull-undistro-build-manager
      branches:
        - main
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        bucket: 'gs://getup-prow-logs-dev'
        path_strategy: explicit
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - manager
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test
        
    - name: pull-undistro-build-CLI
      branches:
        - main        
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        bucket: 'gs://getup-prow-logs-dev'
        path_strategy: explicit
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - cli
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test
        
    - name: pull-undistro-test
      branches:
        - main
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      spec:
        containers:
          - image: 'golang:1.16'
            command:
              - make
              - test
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high  
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: pr-test
        
    - name: undistro-release
      branches:
        - ^v\d+\.\d+\.\d+$
      always_run: true
      optional: false
      decorate: true
      decoration_config:
        ssh_key_secrets:
          - prow-ssh-secret
        timeout: 5h0m0s
      clone_uri: 'git@github.com:getupio-undistro/undistro.git'
      path_alias: github.com/getupio-undistro/undistro
      labels:
        preset-dind-enabled: "true"
        preset-gh-token: "true"
      spec:
        containers:
          - image: 'getupioundistro/undistro-e2e'
            command:
              - "make"
              - "release"
            securityContext:
              privileged: true
              runAsUser: 0
        nodeSelector:
          cloud.google.com/gke-nodepool: undistro-dev-gke-node-pool-high  
      annotations:
        testgrid-dashboards: undistro
        testgrid-tab-name: release            
