version: 2
updates:
  # Daily updates for main go.mod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Weekly updates for everything else
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/UI"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
