area:
  - 'cluster'
  - 'helm'
  - 'cluster-api'
  - 'CLI'
  - 'security'
  - 'docs'

kind:
  - 'bug'
  - 'feature'
  - 'chore'

priority:
  - 'low'
  - 'mid'
  - 'high'

# File globs for PR labeler
tests:
  - '*/test.go'

source:
  - '*'