{{- with .Values.charts.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: undistro-config
  namespace: undistro-system
data:
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
{{- end }}