---
apiVersion: v1
kind: Secret
metadata:
  name: idp-credentials
  namespace: {{ .Values.identity.namespace }}
type: secrets.pinniped.dev/oidc-client
data:
  clientID: {{ .Values.identity.credentials.clientID | b64enc }}
  clientSecret: {{ .Values.identity.credentials.clientSecret | b64enc }}