{{- if and .Values.ingress.enabled .Values.identity.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- if not .Values.local }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
  name: undistro-ingress-identity
  namespace: {{ .Values.identity.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: pinniped-supervisor
                port:
                  number: 80
            path: /auth
            pathType: Prefix
  tls:
    -
      hosts:
      {{with .Values.ingress.ipAddresses}}
      {{- range . }}
        - {{ . }}
      {{- end }}
      {{end}}
      {{- range .Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end -}}