# permissions for end users to edit awsmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsmachine-editor-role
rules:
- apiGroups:
  - metadata.undistro.io
  resources:
  - awsmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metadata.undistro.io
  resources:
  - awsmachines/status
  verbs:
  - get
