# permissions for end users to view awsmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsmachine-viewer-role
rules:
- apiGroups:
  - metadata.undistro.io
  resources:
  - awsmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metadata.undistro.io
  resources:
  - awsmachines/status
  verbs:
  - get
