apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor
  namespace: undistro-system
  labels:
    app: pinniped-supervisor
spec:
  type: ClusterIP
  selector:
    app: pinniped-supervisor
  ports:
  - name: https
    protocol: TCP
    port: 80
    targetPort: 8080
