{{- with .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: undistro-aws-config
  namespace: undistro-system
data:
  accessKeyID: {{ .accessKeyID | b64enc }}
  secretAccessKey: {{ .secretAccessKey | b64enc }}
  {{- if .region}}
  region: {{ .region | b64enc }}
  {{- end}}
{{- end }}