{{- with .Values.credentials }}
---
apiVersion: v1
data:
  clientId: {{ .clientId | b64enc }}
  clientSecret: {{ .clientSecret | b64enc }}
  subscriptionId: {{ .subscriptionId | b64enc }}
  tenantId: {{ .tenantId | b64enc }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: undistro-azure-config
  namespace: undistro-system
    # namespace: capz-system
  annotations:
    helm.sh/hook: pre-install
type: Opaque
{{- end }}
