local: false
dev: false
prometheus:
  enabled: false
charts: {}
ingress:
  enabled: true
  hosts:
    - localhost
    - ingress.local
    - undistro.local
    - undistro.internal
  tls:
    email: undistro@getup.io
  annotations: {}
resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: "0.5"
    memory: 256Mi
image:
  pullPolicy: IfNotPresent
  pullSecrets: []
global:
  undistroVersion: v0.32.1
  undistroRepository: registry.undistro.io/library
