name: undistro-release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release UnDistro
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: vars from bash
        run: ./hack/version.sh

      - name: docker build and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker build -t getupioundistro/undistro:$GIT_VERSION .
          docker push getupioundistro/undistro:$GIT_VERSION

      - name: push helm chart
        uses: goodsmileduck/helm-push-action@v3
        env:
          SOURCE_DIR: "charts"
          CHART_FOLDER: "undistro"
          FORCE: "True"
          CHARTMUSEUM_URL: "https://charts.undistro.io"
          CHARTMUSEUM_USER: "${{ secrets.HELM_LOGIN }}"
          CHARTMUSEUM_PASSWORD: ${{ secrets.HELM_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
